/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/': RouteRecordInfo<'/admin/dashboard/', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/error_code/cml/': RouteRecordInfo<'/admin/error_code/cml/', '/admin/error_code/cml', Record<never, never>, Record<never, never>>,
    '/admin/error_code/cml/[comment]': RouteRecordInfo<'/admin/error_code/cml/[comment]', '/admin/error_code/cml/:comment', { comment: ParamValue<true> }, { comment: ParamValue<false> }>,
    '/admin/error_code/search/': RouteRecordInfo<'/admin/error_code/search/', '/admin/error_code/search', Record<never, never>, Record<never, never>>,
    '/admin/machine/': RouteRecordInfo<'/admin/machine/', '/admin/machine', Record<never, never>, Record<never, never>>,
    '/admin/machine/note/[index]': RouteRecordInfo<'/admin/machine/note/[index]', '/admin/machine/note/:index', { index: ParamValue<true> }, { index: ParamValue<false> }>,
    '/admin/setting/': RouteRecordInfo<'/admin/setting/', '/admin/setting', Record<never, never>, Record<never, never>>,
    '/admin/setting/activity/': RouteRecordInfo<'/admin/setting/activity/', '/admin/setting/activity', Record<never, never>, Record<never, never>>,
    '/admin/setting/activity/add': RouteRecordInfo<'/admin/setting/activity/add', '/admin/setting/activity/add', Record<never, never>, Record<never, never>>,
    '/admin/setting/area/': RouteRecordInfo<'/admin/setting/area/', '/admin/setting/area', Record<never, never>, Record<never, never>>,
    '/admin/setting/customer/': RouteRecordInfo<'/admin/setting/customer/', '/admin/setting/customer', Record<never, never>, Record<never, never>>,
    '/admin/setting/machine/': RouteRecordInfo<'/admin/setting/machine/', '/admin/setting/machine', Record<never, never>, Record<never, never>>,
    '/admin/setting/machine/[edit]': RouteRecordInfo<'/admin/setting/machine/[edit]', '/admin/setting/machine/:edit', { edit: ParamValue<true> }, { edit: ParamValue<false> }>,
    '/admin/setting/machine/add': RouteRecordInfo<'/admin/setting/machine/add', '/admin/setting/machine/add', Record<never, never>, Record<never, never>>,
    '/admin/setting/region/': RouteRecordInfo<'/admin/setting/region/', '/admin/setting/region', Record<never, never>, Record<never, never>>,
    '/admin/setting/user/': RouteRecordInfo<'/admin/setting/user/', '/admin/setting/user', Record<never, never>, Record<never, never>>,
    '/admin/setting/user/[edit]': RouteRecordInfo<'/admin/setting/user/[edit]', '/admin/setting/user/:edit', { edit: ParamValue<true> }, { edit: ParamValue<false> }>,
    '/admin/setting/user/add': RouteRecordInfo<'/admin/setting/user/add', '/admin/setting/user/add', Record<never, never>, Record<never, never>>,
    '/admin/tutorial/add/[add]': RouteRecordInfo<'/admin/tutorial/add/[add]', '/admin/tutorial/add/:add', { add: ParamValue<true> }, { add: ParamValue<false> }>,
    '/admin/tutorial/edit/[edit]': RouteRecordInfo<'/admin/tutorial/edit/[edit]', '/admin/tutorial/edit/:edit', { edit: ParamValue<true> }, { edit: ParamValue<false> }>,
    '/admin/tutorial/text/': RouteRecordInfo<'/admin/tutorial/text/', '/admin/tutorial/text', Record<never, never>, Record<never, never>>,
    '/admin/tutorial/video/': RouteRecordInfo<'/admin/tutorial/video/', '/admin/tutorial/video', Record<never, never>, Record<never, never>>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
